### PR TITLE
Fix age of retirement for women

### LINKED ISSUE #146: OpenFisca - Uruguay rules review and update
As the Piccolo team
We need to review the rules that we've already created against the information provided by Uruguay to ensure that we have the rules implement correctly.

Things to do:
 - Review the information that has been provided to ensure there's a match
https://drive.google.com/drive/folders/11mdH4DJ_uE1KQLu4P6PWxQlk2TSDjt7Q

### PR DESCRIPTION
**Pull request by Br3nda**
fixes https://github.com/ServiceInnovationLab/Piccolo/issues/146

Our Uruguay logic was making the retirement age lower for every child a woman has. But the rules are actually that you have one less year of working needed for each child you have.

I've fixed the logic and the tests

I also used a bit more Spanish, and i moved some of the complex logic out to OF variables

### CODE REVIEW

**Comment by CharlotteHinton** [comment]
@Br3nda If I enter: 
50 yrs
30 years in country
30 years in work
2 children
Woman

I'd expect the age to be 62-2=60 (as each child is considered a year of work)

The result I'm seeing is 58yrs

**Comment by Br3nda** [comment]
Where are you seeing that? Where are you entering these? 
If you mean, you entered them into Piccolo, then yes, it would still have the old incorrect rules -- because this PR you're reviewing now hasn't been approved or merged or deployed yet. It's waiting for peer review.

**Comment by Br3nda** [comment]
I think the case of:
"50 yrs
30 years in country
30 years in work
2 children
Woman"

would be 60 years. A child is considered to be a year of work. It should not subtracted be from the retirement age AFAICT.  Instead, a woman with 2 children need only work for 28 years. So a woman who worked for 30 years has met the criteria.

We were subtracting it from the retirement age (and still are on the deployed code), but this is wrong. This PR is a change to *stop* doing that and instead do the correct thing, which is to consider a child to be the same as a year of work (but only for women)

**Comment by Br3nda** [comment]
Can you show me where you get the 62 from? I was using the 60 under "Jubilación Común" tab.

image

**Comment by Br3nda** [comment]
Found the description is wrong over in the Piccolo code too. I've made a PR there.
https://github.com/ServiceInnovationLab/Piccolo/pull/188

Can someone check what I've written is, in fact, the rules as per the info from Uruguay?

**Comment by CharlotteHinton** [comment]
I was seeing the 62yrs on 'production'. Based on what you've said above, this makes sense to me and that the number of children affects years worked not the pension age.

**Review by dlouise64 — APPROVED** [review]

**Pull request merged**
